# Generated by Django 5.1.1 on 2024-09-26 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_cart'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='cartId',
            new_name='cart_id',
        ),
    ]
