# Generated by Django 5.1.1 on 2024-10-16 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(default='Đã đặt hàng', max_length=100),
        ),
    ]
