# Generated by Django 5.1.1 on 2024-10-25 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_id',
            field=models.CharField(default=12, max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
